version: '3.7'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/tvseries:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./homer:/www/assets
    ports:
      - 80:8080
    user: 1000:1000
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped