version: '3.7'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/library:/config
      - ./jellyfin/tvseries:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - net
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jellyfin
    networks:
      - net

networks:
  net:
    driver: bridge
