version: '3.7'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/media/tvseries:/data/tvshows
      - ./jellyfin/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    volumes:
      - ./homer:/www/assets
    ports:
      - 80:8080
    user: 1000:1000
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nextcloud:
    image: nextcloud:apache
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
  
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432

  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./transmission:/config
      - ./jellyfin:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
